### ISSUE TITLE
taxtable column order must be tax_id, parent_id, rank, tax_name, ranks

### ISSUE THREAD

**Issue by nhoffman** [fhcrc/taxtastic#104]
@crosenth - guppy classify treats columns of the taxtable as order dependent. Column order must be

tax_id, parent_id, rank, tax_name, ranks...

The current output breaks pplacer/guppy

**Comment by crosenth** [comment]
https://github.com/fhcrc/taxtastic/blob/master/taxtastic/subcommands/taxtable.py#L239
