### ISSUE TITLE
Regular build of a full ncbi taxtable

### ISSUE THREAD

**Issue by crosenth** [fhcrc/taxtastic#105]
Weekly build, upload to a remote location (an aws s3 bucket) and connect to a public url

**Comment by crosenth** [comment]
@nhoffman - Any ideas for this?

**Comment by crosenth** [comment]
A full taxtable is ~ 410 megabytes, 21 M compressed

**Comment by nhoffman** [comment]
@crosenth - I don't think there's a need to do this as a standalone resource. Closing. Feel free to reopen if you want to discuss further.
