### ISSUE TITLE
taxtastic - new versions - in BioConda?

### ISSUE THREAD

**Issue by AjitPS** [fhcrc/taxtastic#106]
Hi, are there any plans of bringing newer versions of `taxtastic` ( `0.6.4` and above) in BioConda? as that only has taxtastic 0.5.4

**Comment by nhoffman** [comment]
As far as I know, none of the authors of Taxtastic created the BioConda version. We're currently working on a significant revision that will be released as 0.8 - that would be a good version to make available, if whoever provided earlier versions in BioConda is willing to do it again.

**Comment by nhoffman** [comment]
Closing - I'm not at all opposed to taxtastic being distributed in BioConda, but as I don't use conda, I don't have plans to do it myself.
