### ISSUE TITLE
update to python 3.6 in docker image 

### ISSUE THREAD

**Issue by nhoffman** [fhcrc/taxtastic#118]

**Comment by nhoffman** [comment]
Will need to provide an argument to install_pplacer.sh to suppress installation of python scripts. pplacer is needed for refpkg-related functions, but the python scripts shipped with pplacer should not be required (should confirm).

**Comment by crosenth** [comment]
https://github.com/fhcrc/taxtastic/commit/e38e2abf55a69f3220a91ccfd299cc4c58c0d35e
