### ISSUE TITLE
Documentation out of sync with code?

### ISSUE THREAD

**Issue by nylander** [fhcrc/taxtastic#121]
Hi,
testing out the Quickstart and taxit (v.0.8.3) dies immediately with error:

`$ taxit new_database -d taxonomy.db`
`... taxit: error: unrecognized arguments: -d`

No mention of the `-d` argument from the output of `taxit new_database --help`, but on http://fhcrc.github.io/taxtastic/commands.html#new-database you give the example (using the `-d`) again. Confusing. What am I missing?

Cheers
Johan

P.S. Other examples exists. E.g., (http://fhcrc.github.io/taxtastic/taxonomy.html) `$ taxit taxtable -d taxonomy.db -t 47770,33945 -o minimal_taxonomy.csv` : No `-d` and `-t` doesn't read comma separated lists.
D.S.

**Comment by Conntrast** [comment]
I have this problem as well. Has anyone found a workaround for this?

**Comment by crosenth** [comment]
Hi nylander, 

You do not need to include the -d flag anymore, just the url path to the database: `taxit new_database taxonomy.db`

I am working right now to update the documentation.  Thank you for raising this Issue.

Hi Conntrast,

Great question.  You will need a taxa.csv file that includes taxonomy ids of the reference sequences you want included in your RefPkg.  The easiest way to generate a taxonomy file is to use the `taxit taxtable` subcommand.  If you just want to test out the process you can find "dummy" taxonomy files in the testfiles directory [tax_table.csv](https://github.com/fhcrc/taxtastic/blob/master/testfiles/tax_table.csv) and [minimal_taxonomy.csv](https://github.com/fhcrc/taxtastic/blob/master/testfiles/minimal_taxonomy.csv).

**Comment by nhoffman** [comment]
@crosenth - can we close this?
