### ISSUE TITLE
ValueError: Table "nodes" is missing from the input database.

### ISSUE THREAD

**Issue by RyloByte** [fhcrc/taxtastic#123]
Hey taxtaxtic team,
I am trying to use taxit and ran into the error in the subject.
I ran:
$ taxit new_database
Which downloaded a fresh taxdump.zip and built ncbi_taxonomy.db
I then ran:
$ taxit taxtable -t custom_ref.ids_only ./taxtastic_db/ncbi_taxonomy.db > custom_ref.taxonomy
Which is when I got the error.
I check in the zip for the nodes.dmp and its there, so I'm not sure what is going on.
Thank you!

**Comment by nhoffman** [comment]
I expect that you have either solved this or moved on - feel free to reopen!
