### ISSUE TITLE
Add subcommand 'get-descendants'

### ISSUE THREAD

**Issue by nhoffman** [fhcrc/taxtastic#126]
Create a subcommand based on https://bitbucket.org/uwlabmed/mkrefpkg/src/master/bin/get_descendants.py (ignore the unused ``--sqlite3 argument``) that provides a list of all taxids descended from a list of parent tax_ids.

**Comment by crosenth** [comment]
https://github.com/fhcrc/taxtastic/commit/2953c5e9a7c791ed1b89943988d09d4a94656920
