### ISSUE TITLE
raxml-ng compatibility

### ISSUE THREAD

**Issue by jgolob** [fhcrc/taxtastic#132]
raxml-ng is a clean-sheet re implementation of raxml that seems faster and more reliable.   https://github.com/amkozlov/raxml-ng

It would be a significant improvement if taxtastic could detect and support raxml-ng's log file output.

**Comment by jgolob** [comment]
I have some sample output and an approach.

**Comment by crosenth** [comment]
Hey Jonathan!  Thanks again for the Issue and PR.  Did you know both raxml-ng and epa-ng use the .bestModel file for placements and optimizations?  See Issue https://github.com/fhcrc/taxtastic/issues/145
