### ISSUE TITLE
Remove official Python 2 support

### ISSUE THREAD

**Issue by crosenth** [fhcrc/taxtastic#138]

**Comment by crosenth** [comment]
@nhoffman - Okay to remove official taxtastic Python 2 as described [here](https://www.python.org/doc/sunset-python-2/) and remove Python 2 Unittests?  Presumably Taxtastic would still function in py2 as the only remaining py2 specific code exists in the unit tests https://github.com/fhcrc/taxtastic/commit/52df6f93ce618ee2aec12ffbeb3b48a8122f3718.

**Comment by nhoffman** [comment]
yes!

**Comment by crosenth** [comment]
https://github.com/fhcrc/taxtastic/pull/137
