### ISSUE TITLE
pplacer error when using taxtastic refpkg

### ISSUE THREAD

**Issue by yifeng-evo** [fhcrc/taxtastic#150]
Hello,

I built a refpkg with taxtastic, but when I run `pplacer -c refpkg alignments.sto`, I saw an error message

```
Uncaught exception: Simple_json.Undefined_key("n_cats")
Fatal error: exception Simple_json.Undefined_key("n_cats")
```
Could you please let me know how I can solve this? Thank you!

**Comment by nhoffman** [comment]
I'm afraid this is a pplacer error that would be better discussed in that repo: https://github.com/matsen/pplacer

I also suspect you'll need to provide a bit more information...
