### ISSUE TITLE
ftp download link times out

### ISSUE THREAD

**Issue by nhoffman** [fhcrc/taxtastic#156]
@crosenth - can you please have a look? I think we might need to replace the ftp url with https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip (https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/).

**Comment by crosenth** [comment]
https://github.com/fhcrc/taxtastic/commit/e1c25ea702977aded09a4199127d11749db5b695

**Comment by crosenth** [comment]
Queued up for next release
