### ISSUE TITLE
update_taxids requires seq_info when just list of taxids would suffice

### ISSUE THREAD

**Issue by tyleraland** [fhcrc/taxtastic#69]
What I want to do is to parse some BLAST output, which gives me one or many staxids per hit, and map each sequence to its species-level taxid

Here is my ideal workflow:
* taxit new_database -d taxdb
* extract taxids from my BLAST output > taxids
* taxit taxtable -d taxdb -t taxids -o taxtable.csv
* map each blast result to its species-level taxi in a script

Unfortunately, rarely, BLAST will give me a taxid not in their taxonomy database (and thus not in the taxdb) so I need to filter it out.

As a consequence, I need to use update_taxids to first clean the taxids list.  However, update_taxids requires that my taxids list be a seq_info csv mapping seqname columns to tax_id columns.  This information doesn't really make sense in my case (a single seqname may map to multiple taxids, but taxtable doesn't need that information).  So three extra steps are required:

* create dummy_seq.info.csv seq_name,tax_id header where each seq_name column is blank
* taxit update_taxids dummy_seqinfo.csv -u remove
* cut the blank seq_name column out, remove the header, remove empty lines

As far as I can tell, the seq_name portion of the seq_info file is not used, but it is required.  If update_taxids allowed a list of taxids it would simplify the interface.

**Comment by nhoffman** [comment]
@crosenth - is this still an issue, or has the behavior been updated since Tyler opened this?

**Comment by crosenth** [comment]
Yes:

positional arguments:
  infile                Input CSV file to process, minimally containing the
                        fields `tax_id`. Rows with missing tax_ids are left
                        unchanged.
...
