### ISSUE TITLE
use local copy of ncbi taxdump

### ISSUE THREAD

**Issue by kbseah** [fhcrc/taxtastic#79]
Hello - I'm using taxtastic because I'm interested in using pplacer to classify short reads against a reference. Is it possible to use a local copy of the NCBI taxdump, instead of downloading it new to make the Sqlite taxonomy database?

**Comment by crosenth** [comment]
Hi Brandon,

If a file named taxdump.zip exists in your --download-dir then it will not be re-downloaded.  

For flexibility, I have pushed two new switches to master (``taxit new_database --taxdump-file`` and `taxit new_database --taxdump-url``) that will be included in the next release (v0.5.6).

Chris

**Comment by kbseah** [comment]
Hello Chris,
Thanks for the quick reply! I will give it a try.
-- Brandon
