### ISSUE TITLE
Migrate to python3

### ISSUE THREAD

**Issue by crosenth** [fhcrc/taxtastic#83]
Plan:

1) run 2to3-2.7 on the package dir
2) run git diff to view differences
3) if 2to3-2.7 does not, update taxit shebang to #!/usr/bin/env python3

**Comment by crosenth** [comment]
Decided to take a stab at this since it only depends on packages that are already python 3 compatible.  It mostly works under python 3.4 with most generic test cases and included unittests. https://github.com/fhcrc/taxtastic/tree/py3

**Comment by crosenth** [comment]
An issue is that it is right now *not* backwards compatible with Python 2 but could be made backwards compatible with a little more work.  

This guide has been helpful: http://python3porting.com/

**Comment by crosenth** [comment]
This is ready to go without backwards compatibility with Python 2.

**Comment by nhoffman** [comment]
python3 compatibility added in v0.8.4
