### ISSUE TITLE
PyPI package out of date?

### ISSUE THREAD

**Issue by wwood** [fhcrc/taxtastic#90]
Hi,

I notice on https://pypi.python.org/pypi/taxtastic that the released version is 0.5.4, and yet on GitHub up to 0.5.7 has been tagged. Is there some reason not to push to pypi? I ask because I'm packaging taxtastic for the GNU Guix package manager and don't wish to package bleeding edge code.

I note also that `python setup.py test` doesn't run any of the tests, so running the tests has be done by  `python -m unittest discover -v`. Which is OK (and all the tests pass on 0.5.7 for me).

Thanks,
ben

**Comment by nhoffman** [comment]
@wwood - thanks for raising this issue. We're in the process of making a number of updates, and we should update PyPi with the next release. 

@crosenth - can you comment on the timeline for a new release?

**Comment by crosenth** [comment]
Yes, v0.6.0 will be released to PyPi in the next few days

**Comment by crosenth** [comment]
https://pypi.python.org/pypi/taxtastic
