### ISSUE TITLE
Remove "group" from UNCLASSIFIED_REGEX_COMPONENTS in ncbi.py

### ISSUE THREAD

**Issue by dhoogest** [fhcrc/taxtastic#93]
Several useful bacterial taxons are flagged as invalid due to the `r'\b[Gg]roup\b'` regex filter in ncbi.py. Given that this term has overlap with taxonomic rank 'species group' among others, it seems inappropriate to include it as an indicator of 'unclassification'.

**Comment by dhoogest** [comment]
@crosenth

**Comment by crosenth** [comment]
List of valid and ranked taxons that will now be included:

<img width="848" alt="screen shot 2017-06-12 at 2 20 31 pm" src="https://user-images.githubusercontent.com/1760683/27059875-ed26d0be-4f8d-11e7-9e01-6123955210f8.png">
