### ISSUE TITLE
add_names subcommand

### ISSUE THREAD

**Issue by crosenth** [fhcrc/taxtastic#96]
- [ ] Add @TatyanaV as a developer - @nhoffman 
- [ ] Pull code out of names.py in uw_blast_16s pipeline
- [ ]  Create add_names unittests

**Comment by dhoogest** [comment]
@nhoffman discussed today as a prerequisite to refactor of uw_taxonomy pipeline

**Comment by nhoffman** [comment]
names can be added in the api
