### ISSUE TITLE
evaluate leaving no_rank taxa in database and expanding on the fly

### ISSUE THREAD

**Issue by nhoffman** [fhcrc/taxtastic#99]
Expanding the no_rank taxa (see taxtastic.ncbi.db_load() and taxtastic.ncbi.adjust_node_ranks()) may be better done on the fly when requesting lineages, and it may also be useful to retrieve the native ncbi representation. It also takes a while to do this when loading the database. As a starting point, let's add an argument ``db_load(expand_ranks=True)`` with a corresponding command line option to set expand_ranks to False. The only tricky part here will be to determine an ordering of the ranks. See https://github.com/fhcrc/taxtastic/blob/master/taxtastic/ncbi.py#L262

**Comment by crosenth** [comment]
What is the pplacer requirement for expanded no_rank taxa?

**Comment by nhoffman** [comment]
done in 0.8.1
